language: python


before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda

install:
    - conda env create -f environment.yml --yes -n test_travis
    - source activate test_travis
    - conda install --yes pytest pytest-cov

script:
    - python -m pytest --cov=./

after_success:
    - curl -s https://codecov.io/bash | bash
